# Generated by Django 2.1.3 on 2020-04-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_is',
            new_name='user_id',
        ),
    ]
